version: '3'

services:

  php:
    working_dir: /app
    build: .
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
  
  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017
    volumes:
        - mongodbtest:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodbtest: